---
title-block: false
format:
  html:
    css: styles.css
---


# Interdisciplinary Data Science (IDS) at UC Berkeley

We are a group of faculty interested in strengthening the community of interdisciplinary data science researchers at UC Berkeley. 
Our faculty use the revolutionary changes in data collection, methods, and the emergence of new phenomena, to advance natural and social science disciplines in ways that lead to new areas of scholarship. Our unifying mission is to leverage data to address pressing questions with social and scientific impact. 

## Our Mailing Lists

We have the following Google Group mailing lists for communicating events and activities:

* [Students and Post-docs](https://groups.google.com/a/lists.berkeley.edu/d/forum/ids_students) -- students and post-docs are welcome to add themselves to this google group to learn about student events
* [IDS Faculty](https://groups.google.com/a/lists.berkeley.edu/d/forum/idsfaculty) -- faculty who are members of the IDS faculty group
* [Affiliated Faculty](https://groups.google.com/a/lists.berkeley.edu/d/forum/ids_affiliates) -- related UC Berkeley faculty who wish to contribute to building the IDS community
* [General mailing list](https://groups.google.com/a/lists.berkeley.edu/d/forum/ids_mailing) -- general purpose mailing list open to the UC Berkeley community. Join by adding yourself to the google group linked here to receive announcements of seminars and other events (groups listed above are automatically part of this mailing list!). You can also search for `ids_mailing` in UC Berkeley's google groups, and add yourself. 

