---
title: "Interdisciplinary Data Science Seminar Series"
format: html
listing:
    id: current
    contents: seminarentries/Current
    type: default
    sort: "date asc"
    sort-ui: false
    filter-ui: false
feed: true
---

## About

The IDSI seminar series for Spring 2026 is **Mondays from 11-12 AM in 775 A Tan Hall**

::: {.callout-important}
## **Room Change for February 23!**

**The seminar on Monday February 23 will be in 100F Hildebrand Hall, in the chemistry library.** 
:::


 [Join Google Groups Mailing List](https://groups.google.com/a/lists.berkeley.edu/d/forum/ids_mailing){.btn .btn-outline-primary .btn role="button"} <!--[Add to Calendar](addcalendar.qmd){.btn .btn-outline-primary .btn role="button"} -->

If you have questions about the seminar or have difficulty signing up for the mailing list contact: [Raja Sengupta](mailto:rajasengupta@berkeley.edu)

You can see all [past seminars here](seminarentries/Past/index.qmd)

## Upcoming Events

::: {#current}
:::

## Other Related Seminars of Interest

The following seminar series held at UC Berkeley are likely to be of interest to the IDS community

* [Berkeley AI Risk](https://berkeley-ai-risk.github.io/speaker-series.html): Talks by experts from academia, civil society, and industry on AI risks and mitigations
* [BIDMaP](https://bidmap.berkeley.edu/seminars-events). See also their [emerging scholars](https://bidmap.berkeley.edu/emerging-scholars-seminars) series of research from post-docs and graduate students. 
* [Computational Biology](https://ccb.berkeley.edu/events/seminars-and-symposia/ccb-seminars)
* [Computational Precision Health](https://computationalhealth.berkeley.edu/events/)